AB#38676 Cleaned up repo and removed unused and unnecessary files and folders
LokiLabs/microsoft-graph-explorer-teams-app pull request #22
Opened 2021-07-22 13:12 UTC by omersayshi

### Overview

This repository was full of unnecessary/useless files and required a clean up.

### Testing Instructions
* Just run the app from the root of the repository 
* Make sure everything works as it's should

2021-07-26 14:59 UTC, lhao03 commented
Not sure how to test this because this is all I see:

in ToolkitApp:
![image](https://user-images.githubusercontent.com/55033656/127011301-eeb32d99-0319-4ee3-a517-93632e88880f.png)

at root:
![image](https://user-images.githubusercontent.com/55033656/127011276-65932686-6555-4c15-878b-65d5f169dad8.png)

2021-07-26 16:48 UTC, AyuAi commented
> Not sure how to test this because this is all I see:
> 
> in ToolkitApp:
> ![image](https://user-images.githubusercontent.com/55033656/127011301-eeb32d99-0319-4ee3-a517-93632e88880f.png)
> 
> at root:
> ![image](https://user-images.githubusercontent.com/55033656/127011276-65932686-6555-4c15-878b-65d5f169dad8.png)

These look like normal screenshots to me; Did you run it in debugger mode? That's what we have all been doing, to my knowledge

2021-07-26 17:03 UTC, lhao03 commented
Currently the teams app doesn't work in debugger mode. 
![image](https://user-images.githubusercontent.com/55033656/127029322-417e75b7-a58d-4c08-a82b-904dd2f7d1e0.png)

This is necessary because connected resource, getting RSC permissions belonging to a resource (basically alot of things) depend on the teams app actually being in teams. Can this be refactored such that it still works in debugger mode? 

> > Not sure how to test this because this is all I see:
> > in ToolkitApp:
> > ![image](https://user-images.githubusercontent.com/55033656/127011301-eeb32d99-0319-4ee3-a517-93632e88880f.png)
> > at root:
> > ![image](https://user-images.githubusercontent.com/55033656/127011276-65932686-6555-4c15-878b-65d5f169dad8.png)
> 
> These look like normal screenshots to me; Did you run it in debugger mode? That's what we have all been doing, to my knowledge

2021-07-26 17:04 UTC, lhao03 requested changes
![image](https://user-images.githubusercontent.com/55033656/127029505-110dc797-3f02-47dc-9a53-b3d48b3fe3c8.png)

why were these files deleted? 

![image](https://user-images.githubusercontent.com/55033656/127029582-a4a61284-b8b2-454c-a741-d16c83981e1c.png)

2021-07-26 21:02 UTC, v-mschramm requested changes

2021-07-26 21:02 UTC, v-mschramm commented on README.md
> +## Which folders are important?
This readme.md file is no longer accurate and cannot be followed.  Please cleanup or remove and indicate the task that has been created to fix this.

2021-07-27 00:15 UTC, AyuAi commented
> ![image](https://user-images.githubusercontent.com/55033656/127029505-110dc797-3f02-47dc-9a53-b3d48b3fe3c8.png)
> 
> why were these files deleted?
> 
> ![image](https://user-images.githubusercontent.com/55033656/127029582-a4a61284-b8b2-454c-a741-d16c83981e1c.png)

Ah, I see what you were saying earlier.

Because `settings.json` was deleted, we can no longer run the app in debugger mode, since that file contained all of the relevant info to do such.

I also have the same issue as you; Cannot run/test the app because of such ^^;

2021-07-27 17:38 UTC, omersayshi commented
Alot of new stuff was added and the structure of the repository has been discussed again. Closing this PR to open up a new one with simpler reductions to avoid errors.

2021-07-27 17:38 UTC, closed without merging