AB#39437 string updates
LokiLabs/microsoft-graph-explorer-teams-app pull request #37
Opened 2021-08-03 22:24 UTC by acchiang

- [ ] Rename "Connected Resource" to "Resource IDs"
- [ ] Include Team ID when there is a Channel ID
- [ ] Error message should say "Please install to a Teams channel or chat instance"
- [ ] Config screen should include the string: :"By installing this app, you are granting it resource-specific consent permission against the Teams channel/chat"

2021-08-04 14:17 UTC, AyuAi requested changes
There's actually a few places that need a re-check on this PR @acchiang since I just merged #15 and so the localization framework is in place / should now be upkept in each new PR if possible 🙏 If you have too much on your plate I don't mind helping out by snagging the responsibility, but I wanted to at least let you know first / leave the option to ya!

The rest of the PR looks good and localization looks good for there too c: LGTM after localization re-review !

2021-08-04 14:17 UTC, ayubun commented on tabs/src/components/TabConfig.jsx
> +        <h4 className = "caption">Select save to finish adding the Graph Explorer Sample Teams app. By installing this app, you are granting it resource-specific consent permission against the Teams
Is there a reason this isn’t a localized variable? 👀

2021-08-04 18:07 UTC, acchiang commented on tabs/src/components/TabConfig.jsx
> +        <h4 className = "caption">Select save to finish adding the Graph Explorer Sample Teams app. By installing this app, you are granting it resource-specific consent permission against the Teams
Nope I just added the string outlined in the ticket and followed the file's standards so far, didn't know this should be localiized! I'll do that

2021-08-04 18:31 UTC, acchiang commented
Thanks for the comments @AyuAi! It's ready for re-review :)

2021-08-05 13:27 UTC, lhao03 reviewed
i got an error about using react hooks in class components, so i changed TabConfig to a function component in this branch https://github.com/LokiLabs/microsoft-graph-explorer-teams-app/tree/interns/lhao03/39437-change-to-functional-compnent and it seems to be working.

![image](https://user-images.githubusercontent.com/55033656/128357639-8d3f907b-22f1-4149-b77a-638a7d11fef3.png)


also are these two ids supposed to be slightly different colors?
![image](https://user-images.githubusercontent.com/55033656/128357386-09ec72cd-68ac-47bb-bca5-298a0d4ec822.png)

2021-08-05 13:42 UTC, anneguo3 commented
Small copy change request - could we do just "Team ID" and "Channel ID"?

2021-08-05 18:20 UTC, lhao03 commented
@acchiang i made a PR for the functional component, you just need to give it a review! https://github.com/LokiLabs/microsoft-graph-explorer-teams-app/pull/46

2021-08-06 00:16 UTC, lhao03 approved these changes
lgtm!! (～￣▽￣)～

2021-08-06 13:04 UTC, AyuAi approved these changes
Berry noice c: LGTM!

2021-08-06 16:32 UTC, merged